# =================================
# Particle
# =================================

[particle]

length = 500e-9                      # Total Particle length [m]
diameter = 70e-9                     # Particle diameter [m]
swimming_speed = 10e-6               # Only for active particles [m/s]

eta = 0.953e-3                      # Dynamic viscosity [Pa s] 

n_particle = 1.38                   #Particle refractive index 
n_medium = 1.33                     #Medium refractive index

# =================================
# Initial conditions
# =================================

[initial]

x0 = 0.0                            # [m]
y0 = 0.0                            # [m]
z0 = 0.0                            # [m]

theta0_deg = 25.0                   # [deg]
phi0_deg = 25.0                     # [deg]

# =================================
# Flow conditions
# =================================

[flow]

gamma = 1                           # Shear rate [1/s]
plane = "xz"                        

# =================================
# Optical conditions
# =================================

[optics]

wavelength = 1310e-9                 # wavelength [m]
w0 = 1.9e-6                        # Beam radius at focus [m]
laser_power = 25.0e-3              # [W]

beam_axis = [0.0, 0.0, 1.0]
polarization = [0.0,1.0,0.0]

# =================================
# Simulation conditions
# =================================

[simulation]

t0 = 0.0                 # [s]
tf = 300.0               # [s]
n_points = 4000
rtol=1e-9
atol=1e-12

